/**
 * Dispatch API
 * Generated with `routing-controllers-openapi`
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class BaseEntity {
    'id': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            name: 'id',
            baseName: 'id',
            type: 'string',
        }    ];

    static getAttributeTypeMap() {
        return BaseEntity.attributeTypeMap;
    }
}
