/**
 * Dispatch API
 * Generated with `routing-controllers-openapi`
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export class JobUpdate {
    'complexity'?: number;
    'completedAt'?: string;
    'status'?: JobUpdate.StatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            name: 'complexity',
            baseName: 'complexity',
            type: 'number',
        },
        {
            name: 'completedAt',
            baseName: 'completedAt',
            type: 'string',
        },
        {
            name: 'status',
            baseName: 'status',
            type: 'JobUpdate.StatusEnum',
        }    ];

    static getAttributeTypeMap() {
        return JobUpdate.attributeTypeMap;
    }
}

export namespace JobUpdate {
    export enum StatusEnum {
        Pending = 'Pending' as any,
        Processing = 'Processing' as any,
        Completed = 'Completed' as any,
        Failed = 'Failed' as any,
    }
}
